# Generated by Django 4.0.5 on 2022-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='Дата создания сообщения'),
            preserve_default=False,
        ),
    ]
