# Generated by Django 4.0.5 on 2022-07-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pub_date',
        ),
    ]
