# Generated by Django 4.0.6 on 2022-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cartoons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='films',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='soap_opera',
            field=models.BooleanField(default=False),
        ),
    ]
